theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: tr-TR
title: "Çağatay Yücelen"
description: "Simple is better than complex."
baseurl: "" # the subpath of your site, e.g. "/blog"
url: https://cyucelen.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/logo.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: cyucelen # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: yucelencagatay # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Çağatay Yücelen
  picture: /images/pp.jpg
  email:
  twitter: cagatayyucelen
  links:
    - title: Twitter
      url: https://twitter.com/yucelencagatay
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/cyucelen
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/yucelencagatay
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/cyucelen
    icon: fab fa-github-square
