baseURL = "https://acikkaymak.com/"
languageCode = "en-us"
title = ""
theme = "leaneon"
copyright = "Copyright {year}"

[permalinks]
  blog = "/:filename/"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'rrt'
    tabWidth = 4